package app.novalabs.nova

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Test

/** The app's fan picture must match the fan: compare LightFx with vectors generated by the server's nova_rgb. */
class LightFxTest {
    private val v = JSONObject(javaClass.classLoader!!.getResource("fx_vectors.json").readText())

    @Test fun hashMatchesServer() {
        val a = v.getJSONArray("hash")
        for (i in 0 until a.length()) { val r = a.getJSONArray(i)
            assertEquals("h(${r.getInt(0)}, ${r.getLong(1)})", r.getInt(2), LightFx.h(r.getInt(0), r.getLong(1))) }
    }
    @Test fun framesMatchServer() {
        val cs = v.getJSONArray("cases")
        for (i in 0 until cs.length()) {
            val c = cs.getJSONObject(i); val pal = c.getJSONArray("palette").let { p -> List(p.length()) { p.getString(it) } }
            val fx = LightFx.Fx(c.getString("effect"), c.getInt("led_count"), c.getInt("speed"), c.getBoolean("rainbow"), pal, c.getString("color"), c.getString("color2"))
            val got = LightFx.frame(fx, c.getDouble("t")); val want = c.getJSONArray("out")
            for (j in 0 until want.length()) { val w = want.getJSONArray(j)
                for (k in 0..2) assertEquals("${fx.effect} rb=${fx.rainbow} pal=${pal.size} t=${c.getDouble("t")} led $j ch $k", w.getInt(k), got[j][k]) }
        }
    }
}
